kind: ethereum/contract
name: YeeterTemplate
network:
source:
  abi: YeeterShaman
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  file: ./src/yeeter-mapping.ts
  entities:
    - Yeet
  abis:
    - name: YeeterShaman
      file: ./abis/YeeterShaman.json
  eventHandlers:
    - event: "YeetReceived(indexed address,uint256,address,uint256,uint256)"
      # topic0: "0xa3302eb2d11e39788842421f82fc6c553239f6932e02f0ffe95e85c31c890506"
      handler: handleYeetReceived
